on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  Build
        run: |
          echo "build"
      - name: Test
        run: |
          echo: "Test"
      - name: Deploy
          echo "Deploy"
  Check:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        name: Check
        run: |
          echo "Check"
  
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        name: unit-test
        run: bash.hello.sh